language: node_js
node_js:
- '10'
cache: npm
branchs:
  only:
  - master
install:
- npm install
script:
- npm run build
- rsync -az -vv --delete -e 'ssh -p 22' docs/.vuepress/dist/ ubuntu@iwenson.com:/home/ubuntu/www/public
before_install:
- openssl aes-256-cbc -K $encrypted_6f261d127d87_key -iv $encrypted_6f261d127d87_iv
  -in travis.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
addons:
  ssh_known_hosts: iwenson.com